language: python
python:
  - "3.7"
sudo: required
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk
script:
  - export TAGNAME=$(grep -P "^## .*?" CHANGELOG.md -m1 | awk '{print $2}' |awk '{print $1}')
  - cd docs/
  - pip install -r requirements.txt
  - make latexpdf
  - cd ../
  - if [ "$TRAVIS_BRANCH" = "master" ]; then python setup.py sdist; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then python -m twine upload --username $pypiusername --password $pypipassword dist/*; fi
before_deploy:
 - git tag $TAGNAME
deploy:
 provider: releases
 edge: true
 api_key: $github_access_token
 file_glob: true
 file: docs/build/latex/*.pdf
 cleanup: true
 on:
   repo: riscv/riscv-config
   branch: master
   tags: false
